# Generated by Django 5.1.3 on 2024-12-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_framework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='execution',
        ),
    ]
