# Generated by Django 5.1.3 on 2024-12-04 15:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0004_frameworktheme_delete_framework"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
